acquisition:
  board_num: 0
  chunk_size: 250
  force_channel: 0
  position_channel: 1
  sample_rate_hz: 5000.0
gpio:
  out_alarm: 13
  out_nok: 6
  out_ok: 5
  trigger_pin: 17
scaling:
  force_name: Capteur piézoélectrique
  force_newton_max: 5000.0
  force_unit: N
  force_volt_max: 10.0
  position_mm_max: 98.0
  position_name: Capteur déplacement
  position_unit: mm
  position_volt_max: 10.0
storage:
  data_dir: ./data
thresholds:
  force_max_n: 4500.0
  position_max_mm: 95.0
programmes: {}
